"""Add is_active

Revision ID: 210bb53de308
Revises: 83ad6d6f77c4
Create Date: 2023-04-20 23:42:53.702744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "210bb53de308"
down_revision = "83ad6d6f77c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "USER",
        sa.Column(
            "is_employed", sa.Boolean(), nullable=False, server_default=sa.sql.true()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("USER", "is_employed")
    # ### end Alembic commands ###
