"""Add EMPLOYEE PRESS EMPLOYEE_ROLE

Revision ID: ea6b75090bef
Revises: 210bb53de308
Create Date: 2023-04-22 23:01:34.668517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ea6b75090bef"
down_revision = "210bb53de308"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "EMPLOYEE",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_super_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "PRESS",
        sa.Column("id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("zip_code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "EMPLOYEE_ROLE",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("press_id", sa.String(), nullable=False),
        sa.Column("is_employee", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["EMPLOYEE.id"],
        ),
        sa.ForeignKeyConstraint(
            ["press_id"],
            ["PRESS.id"],
        ),
        sa.PrimaryKeyConstraint("employee_id", "press_id"),
    )
    op.drop_table("USER")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "USER",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(), nullable=False),
        sa.Column("last_name", sa.VARCHAR(), nullable=False),
        sa.Column("nickname", sa.VARCHAR(), nullable=True),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("password", sa.VARCHAR(), nullable=False),
        sa.Column("is_employed", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.drop_table("EMPLOYEE_ROLE")
    op.drop_table("PRESS")
    op.drop_table("EMPLOYEE")
    # ### end Alembic commands ###
