name: Build and Deploy Code

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v3
      - name: Install python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Update pip
        run: pip3 install -U pip
      - name: Install all python dependencies
        run : pip3 install -r requirements.txt
